[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.6"
rapier2d = { version = "0.19.0", features = ["enhanced-determinism"] }

[dependencies.game_logic]
path = "../game_logic"
