[package]
name = "game_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
rapier2d = { version = "0.19.0", features = ["enhanced-determinism"] }

[lib]
name = "game_logic_lib"
path = "src/lib.rs"

[[bin]]
name = "game_logic"
path = "src/main.rs"